export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER'
export const UNSET_AUTHENTICATED_USER = 'UNSET_AUTHENTICATED_USER'
export const SET_FLASH_MESSAGE = 'SET_FLASH_MESSAGE'
export const UNSET_FLASH_MESSAGE = 'UNSET_FLASH_MESSAGE'
